export const coverageRows = [
  {
    name: "Button / IconButton / SplitButton",
    states:
      "Standard 36, compact 32, large 40, ghost, loading, disabled, joined groups",
    responsive: "Wraps",
    keyboard: "Yes",
    use: "Page and record actions",
    ready: "Ready",
  },
  {
    name: "Select / Combobox / MultiSelect",
    states: "Default, compact, disabled, read-only, loading, empty, invalid",
    responsive: "Full-width trigger",
    keyboard: "Arrows, typeahead, Enter, Escape",
    use: "Filters and forms",
    ready: "Ready",
  },
  {
    name: "Country / Nationality Select",
    states: "Search by name, nationality, ISO",
    responsive: "Yes",
    keyboard: "Yes",
    use: "Customer and employee identity fields",
    ready: "Ready",
  },
  {
    name: "PersonSelect",
    states: "Loading, disabled, avatar + subtitle",
    responsive: "Yes",
    keyboard: "Yes",
    use: "Owner and employee pickers",
    ready: "Ready",
  },
  {
    name: "TreeSelect",
    states: "Expand, search, selected",
    responsive: "Yes",
    keyboard: "Yes",
    use: "Hierarchical choices",
    ready: "Ready",
  },
  {
    name: "Dialog / Drawer / Menu / Tooltip",
    states: "Open, busy, Escape, outside click",
    responsive: "Viewport constrained",
    keyboard: "Focus trap, return focus",
    use: "Overlays",
    ready: "Ready",
  },
  {
    name: "DatePicker / DateRangePicker",
    states: "Required, invalid, min/max, disabled dates",
    responsive: "Range collapses",
    keyboard: "Calendar grid",
    use: "Date-only fields",
    ready: "Ready",
  },
  {
    name: "DataTable",
    states: "Default compact 36px rows, sort, select, empty, loading, error, stacked",
    responsive: "Container query stack at ~720px table wrap; internal scroll when columns cannot fit",
    keyboard: "Header buttons",
    use: "Data-list pages",
    ready: "Ready",
  },
  {
    name: "FilterCard / RecordCount",
    states: "Expanded filters, {count} records",
    responsive: "Compact card wraps",
    keyboard: "Named filter region",
    use: "Data-list pages",
    ready: "Ready",
  },
  {
    name: "Layout primitives",
    states: "Stack, grid, collapse, accordion, scroll",
    responsive: "Yes",
    keyboard: "Disclosure",
    use: "Page structure",
    ready: "Ready",
  },
  {
    name: "Display / FormatValue",
    states: "Currency, percent, date, empty",
    responsive: "Yes",
    keyboard: "Tooltip",
    use: "Record fields",
    ready: "Ready",
  },
  {
    name: "Banner / Toast / FeedbackState",
    states:
      "Loading, empty, no results, validation, server error, permission denied, not found, offline, safe retry, unavailable",
    responsive: "Equal-height cards wrap",
    keyboard: "Status/alert roles, retry",
    use: "Page and section feedback",
    ready: "Ready",
  },
  {
    name: "HierarchyPattern",
    states: "Expand, selected, empty, unavailable",
    responsive: "Internal scroll",
    keyboard: "Yes",
    use: "Organization views",
    ready: "Ready",
  },
  {
    name: "PageHeader / RecordDetailHeader",
    states: "Back, status, actions",
    responsive: "Wraps",
    keyboard: "Yes",
    use: "All pages",
    ready: "Ready",
  },
  {
    name: "Charts",
    states: "Ready, loading, empty, error, permission, unavailable",
    responsive: "Internal chart scroll",
    keyboard: "Hover tooltips",
    use: "Performance, reports, dashboards",
    ready: "Ready",
  },
  {
    name: "StageTracker",
    states:
      "Completed, current, upcoming, blocked, failed, rejected, skipped, locked",
    responsive: "Horizontal internal scroll / vertical history",
    keyboard: "Yes",
    use: "Case pipelines and approval history",
    ready: "Ready",
  },
  {
    name: "Export / Import",
    states: "Menu, selected, filtered, preparing, success, failed, validation",
    responsive: "Dialog body scroll",
    keyboard: "Yes",
    use: "CSV and PDF presentation only",
    ready: "Ready",
  },
  {
    name: "Profile identity",
    states:
      "ProfileCoverBanner (recommended header), UserIdentity / ProfileMenu compact refs. ProfileCard is legacy for Sidebar only.",
    responsive: "Wraps",
    keyboard: "Menu",
    use: "Account, assignment, employee headers",
    ready: "Ready",
  },
  {
    name: "Sidebar",
    states: "Expanded, collapsed, active, nested, badge, disabled, drawer",
    responsive: "Internal nav scroll + mobile drawer",
    keyboard: "Arrows, Enter, Escape, focus ring",
    use: "Application shell navigation",
    ready: "Ready",
  },
  {
    name: "Attendance",
    states:
      "Calendar, agenda, off/holiday, CIO, progress, summary, day detail",
    responsive: "Container query: 7-col until ~720px, then AttendanceAgenda",
    keyboard: "Month nav, day select, drawer",
    use: "Attendance pages",
    ready: "Ready",
  },
  {
    name: "Performance",
    states: "Metrics, target, trend, comparison, ranking",
    responsive: "Wraps",
    keyboard: "Chart hover/focus via tooltip",
    use: "Performance pages",
    ready: "Ready",
  },
  {
    name: "Compact values",
    states: "K/M/B/T, currency, percent, negative, tooltip",
    responsive: "Wraps",
    keyboard: "Focus tooltip",
    use: "KPI cards, charts, tables",
    ready: "Ready",
  },
  {
    name: "Profile Banner",
    states:
      "Cover, compact cover, attendance, performance, missing avatar, long name, inactive, actions, white compact",
    responsive: "Container query stacks identity and actions; metadata 3→2 columns",
    keyboard: "Actions, overflow, back",
    use: "Recommended employee, attendance, and performance headers",
    ready: "Ready",
  },
];
