/** Lucide adapter. Design-system components use `DsIcon`, not lucide-react.
 * Charts render SVG primitives and are not a Lucide exception. */
import type { LucideIcon } from "lucide-react";
import {
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Ban,
  Bell,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  CalendarDays,
  ChartColumn,
  ChartNoAxesCombined,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircleAlert,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleSlash,
  CircleUserRound,
  CircleX,
  Clock,
  Contact,
  ContactRound,
  Copy,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FilePlus,
  FileDown,
  FileQuestion,
  FileSpreadsheet,
  FileText,
  FileUp,
  Info,
  LayoutDashboard,
  ListTodo,
  Lock,
  LogIn,
  LogOut,
  Mail,
  MapPin,
  Minus,
  MoreHorizontal,
  Network,
  Package,
  PanelLeftClose,
  PanelLeftOpen,
  Pencil,
  Phone,
  Plus,
  RefreshCw,
  ScrollText,
  Search,
  Settings,
  ShieldOff,
  ShieldX,
  ShieldCheck,
  SlidersHorizontal,
  Trash2,
  TriangleAlert,
  Unlock,
  Upload,
  UserRound,
  UsersRound,
  WalletCards,
  WifiOff,
  Wrench,
  X,
} from "lucide-react";
import { cx } from "./lib/cx";

export const DS_ICON_STROKE = 1.75;

export const dsIconMap = {
  add: Plus,
  edit: Pencil,
  view: Eye,
  hide: EyeOff,
  delete: Trash2,
  close: X,
  back: ArrowLeft,
  forward: ArrowRight,
  more: MoreHorizontal,
  search: Search,
  filter: SlidersHorizontal,
  sort: ArrowUpDown,
  sortAsc: ArrowUp,
  sortDesc: ArrowDown,
  refresh: RefreshCw,
  calendar: CalendarDays,
  time: Clock,
  user: UserRound,
  team: UsersRound,
  organization: Network,
  settings: Settings,
  success: CircleCheck,
  warning: TriangleAlert,
  error: CircleX,
  alert: CircleAlert,
  information: Info,
  offline: WifiOff,
  noAccess: ShieldX,
  notFound: FileQuestion,
  unavailable: CircleSlash,
  maintenance: Wrench,
  created: FilePlus,
  upload: Upload,
  import: FileUp,
  download: Download,
  export: FileDown,
  csv: FileSpreadsheet,
  pdf: FileText,
  copy: Copy,
  external: ExternalLink,
  expand: ChevronDown,
  collapse: ChevronUp,
  previous: ChevronLeft,
  next: ChevronRight,
  locked: Lock,
  unlocked: Unlock,
  noAccessBanner: ShieldOff,
  notification: Bell,
  profile: CircleUserRound,
  branch: MapPin,
  department: Building2,
  signIn: LogIn,
  signOut: LogOut,
  mail: Mail,
  phone: Phone,
  completed: Check,
  current: CircleDot,
  skipped: Minus,
  blocked: Ban,
  dashboard: LayoutDashboard,
  customers: ContactRound,
  cases: BriefcaseBusiness,
  employees: Contact,
  attendance: CalendarCheck,
  tasks: ListTodo,
  performance: ChartNoAxesCombined,
  finance: WalletCards,
  reports: ChartColumn,
  assets: Package,
  administration: ShieldCheck,
  audit: ScrollText,
  help: CircleHelp,
  sidebarClose: PanelLeftClose,
  sidebarOpen: PanelLeftOpen,
} as const;

export type DsIconName = keyof typeof dsIconMap;
export type DsIconSize = 14 | 16 | 18 | 20 | 24;

export function DsIcon({
  name,
  icon,
  size = 16,
  className,
}: {
  name?: DsIconName;
  icon?: LucideIcon;
  size?: DsIconSize;
  className?: string;
}) {
  const Icon = icon ?? (name ? dsIconMap[name] : undefined);
  if (!Icon) return null;
  return (
    <Icon
      className={cx("ds-icon", className)}
      size={size}
      strokeWidth={DS_ICON_STROKE}
      aria-hidden="true"
    />
  );
}

export const dsIconGuide: Array<{
  name: DsIconName;
  meaning: string;
  size: DsIconSize;
}> = [
  { name: "add", meaning: "Add", size: 16 },
  { name: "edit", meaning: "Edit", size: 16 },
  { name: "view", meaning: "View", size: 16 },
  { name: "delete", meaning: "Delete", size: 16 },
  { name: "close", meaning: "Close", size: 16 },
  { name: "back", meaning: "Back", size: 16 },
  { name: "forward", meaning: "Forward", size: 16 },
  { name: "more", meaning: "More actions", size: 16 },
  { name: "search", meaning: "Search", size: 16 },
  { name: "filter", meaning: "Filter", size: 16 },
  { name: "sort", meaning: "Sort", size: 16 },
  { name: "refresh", meaning: "Refresh", size: 16 },
  { name: "calendar", meaning: "Calendar", size: 16 },
  { name: "time", meaning: "Time", size: 16 },
  { name: "user", meaning: "User", size: 16 },
  { name: "team", meaning: "Employees / team", size: 16 },
  { name: "organization", meaning: "Organization", size: 16 },
  { name: "settings", meaning: "Settings", size: 16 },
  { name: "success", meaning: "Success", size: 16 },
  { name: "warning", meaning: "Warning", size: 16 },
  { name: "error", meaning: "Error", size: 16 },
  { name: "information", meaning: "Information", size: 16 },
  { name: "upload", meaning: "Upload / import", size: 16 },
  { name: "download", meaning: "Download / export", size: 16 },
  { name: "csv", meaning: "CSV", size: 16 },
  { name: "pdf", meaning: "PDF", size: 16 },
  { name: "copy", meaning: "Copy", size: 16 },
  { name: "external", meaning: "External link", size: 16 },
  { name: "expand", meaning: "Expand", size: 16 },
  { name: "collapse", meaning: "Collapse", size: 16 },
  { name: "previous", meaning: "Previous", size: 16 },
  { name: "next", meaning: "Next", size: 16 },
  { name: "locked", meaning: "Locked", size: 16 },
  { name: "unlocked", meaning: "Unlocked", size: 16 },
  { name: "notification", meaning: "Notification", size: 16 },
  { name: "profile", meaning: "Profile / account", size: 16 },
  { name: "branch", meaning: "Branch / location", size: 16 },
  { name: "department", meaning: "Department", size: 16 },
  { name: "mail", meaning: "Email", size: 16 },
  { name: "phone", meaning: "Phone", size: 16 },
  { name: "signIn", meaning: "Check in", size: 16 },
  { name: "dashboard", meaning: "Dashboard", size: 18 },
  { name: "customers", meaning: "Customers", size: 18 },
  { name: "cases", meaning: "Cases", size: 18 },
  { name: "employees", meaning: "Employees", size: 18 },
  { name: "attendance", meaning: "Attendance", size: 18 },
  { name: "tasks", meaning: "Tasks", size: 18 },
  { name: "performance", meaning: "Performance", size: 18 },
  { name: "finance", meaning: "Finance", size: 18 },
  { name: "reports", meaning: "Reports", size: 18 },
  { name: "assets", meaning: "Assets", size: 18 },
  { name: "administration", meaning: "Administration", size: 18 },
  { name: "audit", meaning: "Audit", size: 18 },
  { name: "help", meaning: "Help", size: 18 },
  { name: "sidebarClose", meaning: "Collapse sidebar", size: 18 },
  { name: "sidebarOpen", meaning: "Expand sidebar", size: 18 },
];
