"""Bank, Product, Variant and immutable Pipeline input contracts."""

from datetime import date
from uuid import UUID

from pydantic import BaseModel, Field, ValidationInfo, field_validator, model_validator

from app.normalization import display_name, identifier
from app.whole_numbers import NonNegativeWholeAed, WholeCount


def _required_name(value: str) -> str:
    normalized = display_name(value)
    if not normalized:
        raise ValueError("Name is required")
    return normalized


def _required_code(value: str) -> str:
    normalized = identifier(value)
    if not normalized:
        raise ValueError("Code is required")
    return normalized


class BankCreate(BaseModel):
    name: str = Field(min_length=1, max_length=200)

    @model_validator(mode="before")
    @classmethod
    def reject_caller_code(cls, value):
        if isinstance(value, dict) and "bankCode" in value:
            raise ValueError("Bank Code is generated by the server")
        return value

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


class BankUpdate(BaseModel):
    name: str = Field(min_length=1, max_length=200)

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


class ProductCreate(BaseModel):
    code: str = Field(min_length=1, max_length=30)
    name: str = Field(min_length=1, max_length=150)

    @field_validator("code")
    @classmethod
    def normalize_code(cls, value: str) -> str:
        return _required_code(value)

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


class ProductUpdate(BaseModel):
    name: str = Field(min_length=1, max_length=150)

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


class MappingCreate(BaseModel):
    bankId: UUID
    productTypeId: UUID


class VariantCreate(MappingCreate):
    name: str = Field(min_length=1, max_length=150)
    minimumSalaryAed: NonNegativeWholeAed
    maximumSalaryAed: NonNegativeWholeAed

    @field_validator("maximumSalaryAed")
    @classmethod
    def ordered_salary_range(cls, value, info: ValidationInfo):
        if info.data.get("minimumSalaryAed") is not None and value < info.data["minimumSalaryAed"]:
            raise ValueError("Maximum salary must be at least the minimum salary")
        return value

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


class VariantUpdate(BaseModel):
    name: str = Field(min_length=1, max_length=150)
    minimumSalaryAed: NonNegativeWholeAed | None = None
    maximumSalaryAed: NonNegativeWholeAed | None = None

    @field_validator("maximumSalaryAed")
    @classmethod
    def ordered_salary_range(cls, value, info: ValidationInfo):
        minimum = info.data.get("minimumSalaryAed")
        if value is not None and minimum is not None and value < minimum:
            raise ValueError("Maximum salary must be at least the minimum salary")
        return value

    @model_validator(mode="after")
    def complete_salary_range(self):
        if {"minimumSalaryAed", "maximumSalaryAed"} & self.model_fields_set:
            if self.minimumSalaryAed is None or self.maximumSalaryAed is None:
                raise ValueError("Supply both minimum and maximum salary")
        return self

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


class StageCreate(BaseModel):
    name: str = Field(min_length=1, max_length=150)
    stageOrder: int = Field(ge=1)
    expectedBusinessDays: WholeCount = Field(ge=0)
    isFinal: bool = False
    finalStatus: str | None = None

    @field_validator("name")
    @classmethod
    def normalize_name(cls, value: str) -> str:
        return _required_name(value)


MAX_PIPELINE_STAGES = 50


class PipelineCreate(MappingCreate):
    effectiveDate: date
    stages: list[StageCreate] = Field(min_length=2, max_length=MAX_PIPELINE_STAGES)
